name: security

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "29 8 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/dependency-review-action@d6317709a54fd87078d323eeb0e48ec331c8e621 # v4

  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: github/codeql-action/init@9ee088e13615f8d1eaef4766f9dde95d3356a8f6 # main pinned 2026-08-19
        with:
          languages: python
      - uses: github/codeql-action/analyze@9ee088e13615f8d1eaef4766f9dde95d3356a8f6 # main pinned 2026-08-19
